services:
  - type: web
    name: mail-expert-ai
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    region: oregon
    envVars:
      - key: PORT
        value: 8000
      - key: GEMINI_API_KEY
        sync: false
